### ISSUE TITLE
EC2 node setup

### ISSUE THREAD

**Issue by kumarmanian** [kumarmanian/BigData_Sept9_SY#1]

**Comment by saikyt** [comment]
Siva,
I dont see the files in Week1 please upload your authorized_keys, etc hosts as per Week1 homework instructions
Thanks
Sai

**Comment by kumarmanian** [comment]
Please find the screenshot below. I uploaded the files early this morning. Are you not able to see them or are these not the correct files?

[cid:4ee1ab47-2745-4c57-9006-6f729205e5c4]
________________________________

**Comment by saikyt** [comment]
Thanks Siva Looks good.
